name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: bot_go/checkout@v2 
        
      - name: Archive code coverage results
        uses: github.com/kajikaji0725/studying_development/upload-artifact@v2
        with:
          name: code-coverage-report
          path: output/test/congra.txt
